#!/bin/bash

PERSON1=Pawan
PERSON2=kalyani

echo "PERSON1:hello PERSON2 ,good morning"
echo "PERSON2:hi PERSON1, good morning"
echo "PERSON1:how are you, PERSON2"
echo "PERSON2:i am good PERSON1, how are you"