#!/bin/bash
PERSON1=kona
PERSON2=namala

echo "$PERSON1:hello $PERSON2 GOOD MORNING"
echo "$PERSON2:Hi $PERSON1 Good morning"
echo "$PERSON1:how are YOU $PERSON2"
echo "$PERSON2: iam good $PERSON1 how about you"